[package]
name = "rusted-ruins-script"
version = "0.1.0"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
rustpython-vm = { git = "https://github.com/RustPython/RustPython.git", rev = "bc3cc3679c9a53b8a6aa40243d18c604ead47d98" }
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
once_cell = "1"
take_mut = "0.2"

rusted-ruins-common = { path = "../common", features = ["global_state_obj"] }